opening:
  initial_moves: e4

analysis:
  depth: 11
  min_rating: 1600
  max_rating: 1600
  time_controls:
    - blitz
  win_rate_weight: 0.95
  popularity_weight: 0.05
  initial_threshold: 0.02
  position_threshold: 0.05
  min_games: 200
  white_win_rate_threshold: 0.55

api:
  # Cache file is fixed at data/cache.json

output:
  pgn_file: output/blitz_1600.pgn
