opening:
  move: e4
  fen: null

analysis:
  depth: 11
  min_rating: 1600
  max_rating: 1600
  time_controls:
    - blitz
  win_rate_weight: 0.95
  popularity_weight: 0.05
  initial_threshold: 0.02
  position_threshold: 0.05
  min_games: 200
  white_win_rate_threshold: 0.55

api:
  cache_file: data/cache.json
  api_delay: 0.1

output:
  pgn_file: output/blitz_1600.pgn
