opening:
  initial_moves: e4 Nf3

analysis:
  depth: 11
  min_rating: 1600
  max_rating: 1600
  time_controls:
    - blitz
  win_rate_weight: 0.95
  popularity_weight: 0.04
  sharpness_weight: 0.01

  initial_threshold: 0.05
  position_threshold: 0.09

  min_games: 200
  white_win_rate_threshold: 0.60

output:
  pgn_file: output/nf3_1600_blitz.pgn
